### ISSUE TITLE
Initiate a skeleton IG

### ISSUE THREAD

**Issue by liberaliscomputing** [ncpi-fhir/ncpi-fhir-ig#2]
Initiate a skeleton IG as follows:

- [x] Configure SUSHI settings 
- [x] Migrate a Patient example resource(s)
- [x] Migrate a Specimen example resource(s)
- [x] Provide a quick start instruction

**Comment by RobertJCarroll** [comment]
Re publisher:
Name: NCPI FHIR Working Group
URL: https://anvilproject.org/ncpi/working-groups#fhir-working-group
email: <Do we need one or is it just an option?>

I'm not sure on contact- Do you want to be the person for now?

**Comment by RobertJCarroll** [comment]
I presume we can change these at will, so I'm not too worried about it. Please correct me if I'm wrong.

**Comment by liberaliscomputing** [comment]
@RobertJCarroll, yes, it can be updated anytime! `publisher.email` is optional; I will put me as a contact for now. Thanks!
